# Generated by Django 5.0 on 2024-01-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
