# Generated by Django 5.0 on 2024-01-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_purchase_purchase_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
