# Generated by Django 5.0 on 2024-01-20 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_color_size"),
        ("products", "0006_alter_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.color",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.size",
            ),
            preserve_default=False,
        ),
    ]
