# Generated by Django 5.0 on 2024-01-20 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_product_color_product_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="list_name",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="slug",
        ),
    ]
